### ISSUE TITLE
pick some people who can write references for us

### ISSUE THREAD

**Issue by MyBuddyJosia** [zoobean/SBIR#1]
I'm passing around some "assignments" for this SBIR proposal. This one is for Jordan and Felix but looping Claire in as she may be doing the outreach to our references. So we are permitted 3 "letters of endorsement" to support our proposal, and specifically, to speak to the *eventual commercial market potential for our product.* These can come from just about anyone (not internal). For example, future customers (like a school superintendent or school tech lead) or potential investors, or "experts in the field." Even Mark Cuban would qualify—he has to disclose his financial interest in our company but he could still speak to the commercial potential for Hourglass or just voice-interactive Beanstack in general.

This is optional, but if we want to do it (and it can't hurt) **your assignment is: come up with a shortlist of potential references.** Meanwhile, as I write up the proposal, I can use that text to create a letter explaining what we have in mind for this product, and would so-and-so be willing to write a brief note (the limit is 1 page) discussing how great an idea they think it is, and how competent and wonderful we are yada yada (edited) 

Here's the full text of the ask in the application, FYI:
"f. Potential commercial application
After the product is fully developed through Phase I and II R/R&D, briefly describe how it will be commercialized in the private sector marketplace. This description should include examples of how the product will be disseminated to potential end-users and revenue strategies to sustain the product over time.  **Describe how the letters in Appendix I provide initial evidence for a successful plan for the eventual commercialization of the product in the private marketplace.
NOTE:*In Appendix I, offerors may include up to three (3) letters to endorse the significance of the product and the plans for its commercialization in the private market.*
offerors may provide up to three (3) letters to endorse the significance of the proposed product and the potential pathways for commercial dissemination and sustainability of the proposed product. Each letter must not exceed 1-page in length. ...
Notes:  *Strong letters of endorsement (1) state the endorser’s qualifications (e.g., why does this individual/organization have expertise in the area of the proposed product?), (2) refer to the specifics of the proposal, (3) speak to the significance of the proposed product and refer to plans for commercial distribution and sustainability, and (4) may specify future roles or involvement with commercialization down the line (e.g., Phase III) should it be successful.***

Letters endorsing the significance of the proposed product and for potential pathways for its commercial dissemination and sustainability ***may come from individual experts, associations, organizations in the specific field of interest, future potential distribution partners or investors, from schools or districts who would use or possibly purchase the product if it were commercially available, among others.***

As a method to confirm a project team member’s involvement in the project, offerors should not include letters of endorsement from key members of the project team, such as consultants or subcontractors. ... Offerors should not include letters from banks or personal lenders as a means to demonstrate the potential availability of Phase III financing.
...

REQUIRED: Financial Connection Disclosure Requirement
If the endorser and the offeror are currently or were ever financially connected (e.g., the endorsing organization invested in the offeror’s company, the endorsing organization was created specifically to commercialize products developed by the offeror, the endorser paid or is paying the offeror for services or products), the letter of endorsement is required to include a footnote describing the nature of the relationship. This disclosure is intended to clarify for reviewers the precise nature of the relationship between the endorser and the offeror.

Please note: Footnotes are not required in letters where there is no current or prior financial connection between the endorser and offeror.

**Comment by fblloyd** [comment]
@jbookita -- I'd like to do the following:

- [ ] Mark Cuban
- [ ] Stephanie Ham or someone from APS or Broward 
- [ ] Someone from the Alexa Fund

@MyBuddyJosia @jbookita -- What do you think of this list?

@tle105 -- Can you make sure Claire is added to this repository?

**Comment by jbookita** [comment]
I think Stephanie Ham would be the best writer, but Broward does use us with all of their schools and I'm sure Lourdes would love to do it. Not APS, IMHO. FBL, what do you think about those?

**Comment by fblloyd** [comment]
Makes sense to me. Let's see where we are at the end of this week and start reaching out to folks next week. What you think @MyBuddyJosia?

**Comment by MyBuddyJosia** [comment]
One from a school system, one from Alexa, and one from an investor seems like a perfect balance to me. If the Alexa people don't want to do it, then one from Mark and two from schools is probably a good alternative, since schools are the focus of these Ed grants.

**Comment by fblloyd** [comment]
Right on. Thanks.
