### ISSUE TITLE
deliver the technical goals, timeline, and work plan

### ISSUE THREAD

**Issue by MyBuddyJosia** [zoobean/SBIR#2]
I'm gonna need some details from you, @tle105, say next week, on the technical side of this proposal we are making for the SBIR grant. Basically, I need 4 parts:
1. a list of the technical objectives of the project (presumably to make Beanstack voice-interactive, but ideally getting into more specifics about stage-by-stage goals)
2. a timeline of which goals you expect when. Total project time limit is 8 months, but we'd need a working prototype before then so that the academic research team has time to take it to some schools and test it.
3. a work plan (which is kindof a combo of 1 and 2, but I guess explaining what you will actually DO to make sure we hit the goals according to the timeline)
4. Refinement of the prototype: "describe the R/R&D procedures through which a prototype will be developed and fully functioning. Offerors should describe the procedures that will be used to test and refine the prototype"

This shouldn't be a long thing. Less than a page for all 4 combined is a-ok. So you can let me know how you want to swing it. You can write a bullet-point draft and hand me that. We can do a video chat and I can type notes and write it up from there. Whatever is easiest for you. Lemme know

**Comment by MyBuddyJosia** [comment]
@tle105 here's the full ask from the RFP:
" Phase I Technical Objectives 

a. Phase I R/R&D objectives
State the specific objectives of the Phase I R/R&D effort. Clearly identify each of the critical components of the prototype that will be developed in Phase I and what work will be completed in order to have a fully functioning prototype.  The Phase I R/R&D objectives should include activities to test the usability of the prototype and the initial feasibility of the product concept with the intended end-user. 

b. Project timeline
Explain how the proposed objectives will be accomplished within eight months.  A timeline should be included.

3.  Phase I work plan 
Offerors should provide a detailed plan of the technological R/R&D activities that will occur in Phase I, including what will be done, where it will be done, and how it will be carried out.  The Phase I R/R&D plan should address the objectives detailed in Section III.F.2. (Phase I Technical Objectives).  Offerors should make clear how the work plan addresses each of the objectives.

a. Development of the prototype
As part of the plan, offerors should describe the R/R&D procedures through which a prototype will be developed and fully functioning. Offerors should describe the procedures that will be used to test and refine the prototype..."

**Comment by fblloyd** [comment]
@tle105 -- With everything going on this week, whet's the due date you can give @MyBuddyJosia for this one? Can we also get Kuz added to this ticket and let me know what you need from me?

**Comment by tle105** [comment]
@fblloyd We might be able to work on it Friday.  Depends how this last push on Ticket Rewards goes.

**Comment by tle105** [comment]
@kuzin @Coconnell7 Are now added.

**Comment by fblloyd** [comment]
Thanks!

**Comment by tle105** [comment]
hey @MyBuddyJosia here goes a rough first stab at it. let us know what else we should do to help and explain more.

https://docs.google.com/document/d/1_BKraQOmhZ2azxoPX5LgceG_OzpBfFWz3b_NiR0ZaRw/edit?usp=sharing

**Comment by MyBuddyJosia** [comment]
Great @tle105 thank you for driving that out. I will look it over in detail and let you know any questions.
