### ISSUE TITLE
Do we want to use $6500 of grant money for "technical advice?"

### ISSUE THREAD

**Issue by MyBuddyJosia** [zoobean/SBIR#4]
@fblloyd sent you this via slack a while back but moving to a github ticket for ya: 
@tle105 you may also want to read below and sound off. 

An aspect of the SBIR application we haven't yet discussed is the **" technical assistance provider"**. Basically we can spend up to $6500 on a 3rd party who helps us connect with other resources (like engineers or special training). Not sure if we need or want to pursue it(?). Here are the specifics:

"... the fall of 2018, ED now provides awardees the option to use part of the Phase I and II awards for technical assistance for specialized strategic business training.
If offerors choose to utilize a technical assistance provider/vendor, the offeror is required to include this vendor as a consultant in the budget and to provide a detailed budget justification.  (Please note – offerors are not required to utilize funding for this purpose.)
Offeror’s may request a maximum of $6,500 per year for a Phase I and a maximum of $50,000 per Phase II project (across all years) for assistance.
Reimbursement is limited to services received that comply with 15 U.S.C. § 638(q), as follows:
**To provide small business concerns engaged in SBIR projects with technical and business assistance services, such as access to a network of scientists and engineers engaged in a wide range of technologies, product sales, IP protections, market research, market validation, development of regulatory plans, manufacturing plans, or access to technical and business literature available through on-line data bases, for the purpose of assisting such concerns in:
making better technical decisions concerning such projects;
solving technical problems which arise during the conduct of such projects;
minimizing technical risks associated with such projects; and
developing and commercializing new commercial products and processes resulting from such projects, including intellectual property protections.**
To request technical assistance from a provider:
Label the requested cost “Technical Assistance” in the Budget line “Technical Assistance.:
In Appendix H, provide a detailed description (1-page maximum) of the technical or business assistance that the vendor will provide, including the name of the vendor and the expected benefits and results of the technical or business assistance."

**Comment by fblloyd** [comment]
I think we tabled this one during our call today @MyBuddyJosia
